// GENERATED by tools/bake_radar.js — do not edit by hand.
// World-space placement of assets/radar_chart.png for the HUD terrain radar.
export const RADAR_CHART = {
  file: 'assets/radar_chart.png',
  centerX: 48000,
  centerZ: -28000,
  mpp: 100,
  size: 2048,
};
